Tried numba to accelerate the code.
autojit failes with
AttributeError: class Bunch has no attribute '__mro__'
Probably, pyquante classes are old, needs to inherit object
like new classes in Python.
@jit failes with
ValueError: callable CPUDispatcher(<function getLocalNnzInfo at 0x1170ee938>) is not supported by signature

Conclusion: numba doesn't work out of the box for now.